In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()  # for plot styling
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.decomposition import PCA, FastICA

In [2]:
#https://www.springboard.com/blog/beginners-guide-neural-network-in-python-scikit-learn-0-18/  
MY_FILE = 'iris.csv'
df = pd.read_csv(MY_FILE)
speices = {'Iris-setosa': 1,'Iris-versicolor': 2, 'Iris-virginica' :3 } 
df.speices = [speices[item] for item in df.speices] 
print(df.columns.values)
print(df.head(10))
print(df.shape)

['sepal_length' 'sepal_width' 'petal_length' 'petal_width' 'speices']
   sepal_length  sepal_width  petal_length  petal_width  speices
0           5.1          3.5           1.4          0.2        1
1           4.9          3.0           1.4          0.2        1
2           4.7          3.2           1.3          0.2        1
3           4.6          3.1           1.5          0.2        1
4           5.0          3.6           1.4          0.2        1
5           5.4          3.9           1.7          0.4        1
6           4.6          3.4           1.4          0.3        1
7           5.0          3.4           1.5          0.2        1
8           4.4          2.9           1.4          0.2        1
9           4.9          3.1           1.5          0.1        1
(150, 5)


In [3]:
X = df.drop('speices',axis=1)
y = df['speices']



In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y)



In [5]:
scaler = StandardScaler()

In [6]:
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [7]:
# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
mlp = MLPClassifier(hidden_layer_sizes=(18,18,18),max_iter=500)

In [9]:
mlp.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(18, 18, 18), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [10]:
predictions = mlp.predict(X_test)

In [11]:
from sklearn.metrics import classification_report,confusion_matrix

In [12]:
print(confusion_matrix(y_test,predictions))

[[18  0  0]
 [ 0  8  1]
 [ 0  0 11]]


In [13]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          1       1.00      1.00      1.00        18
          2       1.00      0.89      0.94         9
          3       0.92      1.00      0.96        11

avg / total       0.98      0.97      0.97        38



In [14]:
len(mlp.coefs_)

4

In [15]:
len(mlp.coefs_[0])

4

In [16]:
len(mlp.intercepts_[0])

18

In [40]:
pca = PCA(n_components=2)

In [41]:
X_pca_train = pca.fit_transform(X_train)
X_pca_test = pca.fit_transform(X_test)

In [42]:
print(X_pca_train.shape)

(112, 2)


In [43]:
mlp.fit(X_pca_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(18, 18, 18), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [44]:
predictions = mlp.predict(X_pca_test)

In [45]:
print(confusion_matrix(y_test,predictions))

[[ 0  0 18]
 [ 4  5  0]
 [11  0  0]]


In [46]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          1       0.00      0.00      0.00        18
          2       1.00      0.56      0.71         9
          3       0.00      0.00      0.00        11

avg / total       0.24      0.13      0.17        38

