In [24]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()  # for plot styling
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.decomposition import PCA, FastICA

In [25]:
#https://www.springboard.com/blog/beginners-guide-neural-network-in-python-scikit-learn-0-18/    
MY_FILE = 'winequality-red.csv'
df = pd.read_csv(MY_FILE, sep=';')
print(df.columns.values)
print(df.head(10))
print(df.shape)

['fixed acidity' 'volatile acidity' 'citric acid' 'residual sugar'
 'chlorides' 'free sulfur dioxide' 'total sulfur dioxide' 'density' 'pH'
 'sulphates' 'alcohol' 'quality']
   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   
5            7.4              0.66         0.00             1.8      0.075   
6            7.9              0.60         0.06             1.6      0.069   
7            7.3              0.65         0.00             1.2      0.065   
8            7.8              0.58         0.02             2.0      0.073   
9            7.5              0.50         0.3

In [26]:
X = df.drop('quality',axis=1)
y = df['quality']



In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y)



In [28]:
scaler = StandardScaler()

In [29]:
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [30]:
# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [31]:
mlp = MLPClassifier(hidden_layer_sizes=(18,18,18),max_iter=500)

In [32]:
mlp.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(18, 18, 18), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [33]:
predictions = mlp.predict(X_test)

In [34]:
from sklearn.metrics import classification_report,confusion_matrix

In [35]:
print(confusion_matrix(y_test,predictions))

[[  0   2   0   1   0   0]
 [  0   0  12   2   0   0]
 [  0   2 132  32   3   0]
 [  0   1  44  91  27   0]
 [  0   0   1  20  22   0]
 [  0   0   0   4   4   0]]


In [36]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          3       0.00      0.00      0.00         3
          4       0.00      0.00      0.00        14
          5       0.70      0.78      0.74       169
          6       0.61      0.56      0.58       163
          7       0.39      0.51      0.44        43
          8       0.00      0.00      0.00         8

avg / total       0.58      0.61      0.60       400



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [37]:
len(mlp.coefs_)

4

In [38]:
len(mlp.coefs_[0])

11

In [39]:
len(mlp.intercepts_[0])

18

In [40]:
pca = PCA(n_components=5)

In [41]:
X_pca_train = pca.fit_transform(X_train)
X_pca_test = pca.fit_transform(X_test)

In [42]:
print(X_pca_train.shape)

(1199, 5)


In [43]:
mlp.fit(X_pca_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(18, 18, 18), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [44]:
predictions = mlp.predict(X_pca_test)

In [45]:
print(confusion_matrix(y_test,predictions))

[[  0   0   3   0   0   0]
 [  0   0  11   2   1   0]
 [  0   0 119  47   3   0]
 [  0   0  56  92  15   0]
 [  0   0   7  26  10   0]
 [  0   0   0   5   3   0]]


In [46]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          3       0.00      0.00      0.00         3
          4       0.00      0.00      0.00        14
          5       0.61      0.70      0.65       169
          6       0.53      0.56      0.55       163
          7       0.31      0.23      0.27        43
          8       0.00      0.00      0.00         8

avg / total       0.51      0.55      0.53       400



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
